---
all:
  children:
    workstation:
      hosts:
        localhost:
          ansible_connection: local

    rhel_managed:
      children:
        rhel_sandbox:
          hosts:
            rhel10-test01:
              ansible_connection: ssh

        rhel_infrastructure:
          children:
            dns_servers:
              children:
                dns_primaries:
                  hosts:
                    dns01:
                      ansible_connection: ssh

                dns_secondaries:
                  hosts:
                    dns02:
                      ansible_connection: ssh
            vault_servers:
              hosts:
                vault01:
                  ansible_connection: ssh

            load_balancers:
              hosts:
                lb01:
                  ansible_connection: ssh

    ubuntu_managed:
      children:
        ubuntu_sandbox:
          hosts:
            ubuntu-test01:
              ansible_connection: ssh
